name: issues

on:
  issues:
    types: [opened, reopened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: "notify: new"
        if: github.event.issue.state == 'open'
        uses: calamares/actions/matrix-notify@v3
        with:
          token: ${{ secrets.MATRIX_TOKEN }}
          room: ${{ secrets.MATRIX_ROOM }}
          message: "OPENED ${{ github.event.issue.html_url }} by ${{ github.actor }} ${{ github.event.issue.title }}"
      - name: "notify: closed"
        if: github.event.issue.state != 'open'
        uses: calamares/actions/matrix-notify@v3
        with:
          token: ${{ secrets.MATRIX_TOKEN }}
          room: ${{ secrets.MATRIX_ROOM }}
          message: "CLOSED ${{ github.event.issue.html_url }} by ${{ github.actor }} ${{ github.event.issue.title }}"
      - name: "remove in-progress label"
        if: github.event.issue.state != 'open'
        run: |
          curl -X DELETE \
            -H 'Accept: application/vnd.github.v3+json' \
            -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels/hacking%3A%20in-progress"

