name: weekly-debian-11

on:
  schedule:
    - cron: "12 11 * * 3"
  workflow_dispatch:

env:
  BUILDDIR: /build
  SRCDIR: ${{ github.workspace }}
  CMAKE_ARGS: |
    -DKDE_INSTALL_USE_QT_SYS_PATHS=ON
    -DCMAKE_BUILD_TYPE=Debug
    -DBUILD_APPSTREAM=ON
    -DBUILD_APPDATA=ON
    -DBUILD_TESTING=ON

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://debian:11
      options: --tmpfs /build:rw --user 0:0
    steps:
      - name: "prepare git"
        shell: bash
        run: |
            apt-get update
            apt-get -y install git-core jq curl
            apt-get -y install pylint python3-pylint-common
      - name: "prepare source (core)"
        uses: calamares/actions/generic-checkout@v5
      - name: "prepare source (extensions)"
        shell: bash
        run: git clone https://github.com/calamares/calamares-extensions.git ${SRCDIR}/calamares-extensions
      - name: "install dependencies"
        shell: bash
        run: ./ci/deps-debian11.sh
      - name: "build (core)"
        shell: bash
        run: ./ci/build.sh
      - name: "build (extensions)"
        shell: bash
        run: BUILDDIR=/build/calamares-extensions SRCDIR=${SRCDIR}/calamares-extensions ./ci/build.sh
      - name: "test (core)"
        shell: bash
        run: ctest --test-dir /build -V
